Move test for grub-dir to after we installed the deb!

diff --git a/efi-install b/efi-install
--- a/efi-install
+++ b/efi-install
@@ -140,9 +140,6 @@ main() {
         esac
     fi
 
-    local arch_dir=$GRUB_DIR/$arch-efi
-    test -d $arch_dir || fatal "Could not find directory %s" "$(eq $arch_dir)"
-
     #---- Find the ESP partition to use
     : ${esp_part:=$(get_drive $root_part)}
     check_dev $esp_part "ESP partition/drive"
@@ -188,6 +185,11 @@ main() {
             test -r $MNTPNT$deb_file && pretend chroot $MNTPNT /usr/bin/dpkg -i $deb_file
             touch $did_extract
         fi
+
+
+        local arch_dir=$GRUB_DIR/$arch-efi
+        test -d $MNTPNT$arch_dir || fatal "Could not find directory %s" "$(eq $arch_dir)"
+
         pretend chroot $MNTPNT /usr/sbin/grub-install --target=$arch-efi --efi-directory=$EFI_DIR --boot-directory=$EFI_DIR --bootloader-id="$NAME" 2>&1
         pretend chroot $MNTPNT /usr/sbin/grub-mkconfig -o /boot/efi/grub/grub.cfg 2>&1
 
