add find-esps command for finding multiple esps

diff --git a/partition-info b/partition-info
--- a/partition-info
+++ b/partition-info
@@ -2,9 +2,6 @@
 
 ME=${0##*/}
 
-VERSION="1.10.00"
-VERSION_DATE="Fri Feb 15 13:16:12 MST 2019"
-
 MAJOR_LIST="3,8,22,179,202,254,259"
 # See the Linux kernel file Documentation/devices.txt for device numbers
 #
@@ -24,13 +21,6 @@ MAJOR_LIST="3,8,22,179,202,254,259"
 # 129 block SCSI disk devices (144-159)
 # ...
 # 135 block SCSI disk devices (240-255)A
-#
-# 240-254 block	LOCAL/EXPERIMENTAL USE
-#		Allocated for local/experimental use.  For devices not
-#		assigned official numbers, these ranges should be
-# used in order to avoid conflicting with future assignments
-#
-# 254 block used by QEMU/KVM
 #
 # 259 block	Block Extended Major  Used dynamically to hold additional partition
 #     minor numbers and allow large numbers of partitions per device
@@ -77,6 +67,13 @@ Commands:
         found or not. An empty string sigifies no ESP partition was found.
         Failure indicates a problem with the command line argument or a
         non-existent device.
+        
+    find-esps=<device>
+        Print the name of all ESP partitions on the same disk device 
+        as <device>.  Returns success whether an ESP partition was
+        found or not. An empty string sigifies no ESP partition was found.
+        Failure indicates a problem with the command line argument or a
+        non-existent device.
 
     is-linux=<device>
         Determine if <device> is a Linux partition.
@@ -91,8 +88,6 @@ Commands:
         Display information for all swap partitions
 
 Options:
-    -a, --add-major=<num>
-        Add <num> to the list of major devices
 
     -d, --dev-output
         Add /dev/ to device names in lists.
@@ -129,9 +124,6 @@ Options:
 
     -t, --tabs
         Tab delimit output.
-
-    -t, --version
-        Show version and exit
 Usage
 
     exit $ret
@@ -143,7 +135,7 @@ main() {
 
     local SHIFT DEV_OUTPUT MIN_SIZE TAB_DELIMIT EXCLUDE SIMPLIFY=true
     local EX_BOOT EX_EFI EX_SWAP FULL_FIELDS SHOW_HEADER=true
-    local SHORT_STACK="adefhmMnrtv"
+    local SHORT_STACK="defhmMnrt"
 
     # Allow options before and after the command
     read_params "$@"
@@ -192,6 +184,7 @@ main() {
              drives) do_drives                    ;;
           is-linux*) do_is_linux $cmnd            ;;
       split-device*) do_split_device $cmnd        ;;
+          find-esps*) do_find_esps $cmnd		  ;;
           find-esp*) do_find_esp $cmnd            ;;
                swap) ONLY_SWAP=true; do_all_parts ;;
                   *) do_parts $cmnd               ;;
@@ -203,8 +196,6 @@ main() {
 eval_argument() {
     local arg=$1 val=$2
         case $arg in
-         -add-major|a) add_major "$val"   ;;
-         -add-major=*) add_major "$val"   ;;
         -dev-output|d) DEV_OUTPUT=/dev/   ;;
               -help|h) usage              ;;
            -exclude|e) EXCLUDE=$val       ;;
@@ -215,9 +206,8 @@ eval_argument() {
          -major-num|M) MAJOR_LIST=$val    ;;
      -major-num=*|M=*) MAJOR_LIST=$val    ;;
         -noheadings|n) SHOW_HEADER=       ;;
-               -raw|r) SIMPLIFY=          ;;
+               -raw|r) SIMPLIFY=      ;;
               -tabs|t) TAB_DELIMIT=true   ;;
-           -version|v) show_version       ;;
                     *) fatal "Unknown parameter -$arg" ;;
     esac
 }
@@ -225,7 +215,6 @@ eval_argument() {
 takes_param() {
     case $1 in
         -exclude|-major-num|-min-size|[emM]) return 0 ;;
-                               -add-major|a) return 0 ;;
     esac
     return 1
 }
@@ -242,6 +231,20 @@ do_find_esp() {
 
     local expr="(c12a7328-f81f-11d2-ba4b-00a0c93ec93b|0xef)$"
     lsblk -nlo name,parttype /dev/$drive | egrep "$expr" | head -n1 | awk '{print $1}'
+}
+
+do_find_esps() {
+    local cmnd=$1  dev=${1#find-esps=}
+
+    [ ${#dev} -eq 0 -o "$cmnd" = "$dev" ] && fatal "Must use \"find-esps=<device>\""
+    dev=${dev#/dev/}
+
+    local drive=$(get_drive $dev)
+    [ ${#drive} -gt 0 ] || fatal "No root device name found"
+    test -b /dev/$drive || fatal "Root device /dev/$drive not found"
+
+    local expr="(c12a7328-f81f-11d2-ba4b-00a0c93ec93b|0xef)$"
+    lsblk -nlo name,parttype /dev/$drive | egrep "$expr" | awk '{print $1}'
 }
 
 do_split_device() {
@@ -557,24 +560,6 @@ all_labels() {
 fatal() {
     echo "$ME fatal error: $*"
     exit 2
-}
-
-add_major() {
-    # spaces to commas
-    add=${1// /,}
-
-    # append and remove repeated commas
-    MAJOR_LIST=$(echo "$MAJOR_LIST,$add" | tr -s ",")
-
-    # remove trailing comma
-    MAJOR_LIST=${MAJOR_LIST%,}
-}
-
-show_version() {
-    local fmt="%s: version %s (%s)\n"
-    printf "$fmt" "$ME" "$VERSION" "$VERSION_DATE"
-    printf "Major devices: %s\n" "$MAJOR_LIST"
-    exit 0
 }
 
 #-------------------------------------------------------------------------------
